server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
 
  error:
    include-stacktrace: always
    include-message: always


spring:
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/sorigalpi?serverTimezone=Asia/Seoul
    #url: jdbc:mysql://localhost:3306/test2?serverTimezone=Asia/Seoul
   username: root
   password: 1234
    #password: 0930
  redis:
    host: localhost
    port: 6379
   
   # 스웨거 스프링부트 버전2.6이후 생기는 오류를 해결해주는 설정    
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: true
    

#Jwt Secret Key
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHadERWEFDSFAWEFQWEFQWEG
